### ISSUE TITLE
Can't install in Steam Link

### ISSUE THREAD

**Issue by rolivav** [milaq/steamlink_VirtualHereFreeInstaller#2]
Hey, I put the gz file in `steam/apps` in a FAT32 pendrive, connected it into the Steam Link and disconnected/reconnected the device.
It goes directly into the Checking network prompt, I don't get an install menu.

Is there anything else needed? Maybe the file needs the right permissions? I'm doing it from Windows btw, that might be a problem.

**Comment by Miloune** [comment]
Hello,
Did it myself today and it works like a charm. Be carefull you said folder "steam/apps" but it's "steamlink/apps". When you start your steamlink, you will find a new icon right after your computer icon. Click it, it will install VirtualHere and restart.

**Comment by rolivav** [comment]
Hey it actually worked perfectly, I just forgot to close this ticket :) great job!
